function fncUpadteUserprofile() {
    $("flasherror").innerHTML = "";
    $("errordisplay").innerHTML = "";
    $("flashsuccess").innerHTML = "";
    $("flashsuccess").hide();
    $("close_button_success").hide();
    if (!1 == is_field_empty("txtFirstName", "Please enter First Name", "errordisplay", "close_button") || !1 == is_field_empty("txtLastName", "Please enter Last Name", "errordisplay", "close_button") || !1 == is_field_empty("forumalias", "Please enter Forum Alias", "errordisplay", "close_button") || !1 == is_field_empty("txtPhone", "Please enter Phone Number", "errordisplay", "close_button")) return !1;
    if (10 > $("txtPhone").value.length) return $("errordisplay").style.display = "block",$("close_button").style.display = "block",$("errordisplay").innerHTML = "Phone Number should contain minimum 10 numbers", $("txtPhone").focus(), !1;
    $("errordisplay").style.display = "none";$("close_button").style.display = "none";
    if (!1 == is_field_empty("s_txtAddress", "Please enter Shipping Address", "errordisplay", "close_button") || !1 == is_field_empty("s_txtCity", "Please enter shipping City", "errordisplay", "close_button") || !1 == is_drop_down_empty("cmbstate_s", "Please select shipping State", "errordisplay", "close_button") || !1 == is_field_empty("s_txtZip", "Please enter shipping Zip Code", "errordisplay", "close_button")) return !1;
    if (!0 == checkzip($("s_txtZip"))) {
        if (!0 == IsNumeric($("s_txtZip").value)) { $("errordisplay").style.display = "none";$("close_button").style.display = "none";}
        else return $("errordisplay").style.display = "block",$("close_button").style.display = "block", $("errordisplay").innerHTML = "Shipping Zipcode must be 5 digits", $("s_txtZip").focus(), !1;
        $("errordisplay").style.display = "none";$("close_button").style.display = "none";
    } else return $("errordisplay").style.display = "block",$("close_button").style.display = "block", $("errordisplay").innerHTML = "Shipping Zipcode must be 5 digits", $("s_txtZip").focus(), !1; if (!1 == is_field_empty("b_txtAddress", "Please enter Billing Address", "errordisplay", "close_button") || !1 == is_field_empty("b_txtCity", "Please enter billing City", "errordisplay", "close_button") || !1 == is_drop_down_empty("cmbstate_b", "Please select billing State", "errordisplay", "close_button") || !1 == is_field_empty("b_txtZip", "Please enter billing Zip Code", "errordisplay", "close_button")) return !1;
    if (!0 == checkzip($("b_txtZip"))) {
        if (!0 == IsNumeric($("b_txtZip").value)) { $("errordisplay").style.display = "none";$("close_button").style.display = "none";}
        else return $("errordisplay").style.display = "block",$("close_button").style.display = "block", $("errordisplay").innerHTML = "Billing Zipcode must be 5 digits", $("b_txtZip").focus(), !1;
        $("errordisplay").style.display = "none";$("close_button").style.display = "none";
    } else return $("errordisplay").style.display = "block",$("close_button").style.display = "block", $("errordisplay").innerHTML = "Billing Zipcode must be 5 digits", $("b_txtZip").focus(), !1;
    $("frmadhischool").action = base_url + "index.php/profile/update_profile/";
    $("frmadhischool").submit()
}
/*; function fncUpadteUserprofile(){$("flasherror").innerHTML="";$("errordisplay").innerHTML="";$("flashsuccess").innerHTML="";if(!1==is_field_empty("txtFirstName","Please enter First Name","errordisplay")||!1==is_field_empty("txtLastName","Please enter Last Name","errordisplay")||!1==is_field_empty("forumalias","Please enter Forum Alias","errordisplay")||!1==is_field_empty("txtPhone","Please enter Phone Number","errordisplay"))return!1;if(10>$("txtPhone").value.length)return $("errordisplay").style.display= "block",$("errordisplay").innerHTML="Phone Number should contain minimum 10 numbers",$("txtPhone").focus(),!1;$("errordisplay").style.display="none";if(!1==is_field_empty("s_txtAddress","Please enter Shipping Address","errordisplay")||!1==is_field_empty("s_txtCity","Please enter shipping City","errordisplay")||!1==is_drop_down_empty("cmbstate_s","Please select shipping State","errordisplay")||!1==is_field_empty("s_txtZip","Please enter shipping Zip Code","errordisplay"))return!1;if(!0==checkzip($("s_txtZip"))){if(!0== IsNumeric($("s_txtZip").value))$("errordisplay").style.display="none";else return $("errordisplay").style.display="block",$("errordisplay").innerHTML="Shipping Zipcode must be 5 digits",$("s_txtZip").focus(),!1;$("errordisplay").style.display="none"}else return $("errordisplay").style.display="block",$("errordisplay").innerHTML="Shipping Zipcode must be 5 digits",$("s_txtZip").focus(),!1;if(!1==is_field_empty("b_txtAddress","Please enter Billing Address","errordisplay")||!1==is_field_empty("b_txtCity", "Please enter billing City","errordisplay")||!1==is_drop_down_empty("cmbstate_b","Please select billing State","errordisplay")||!1==is_field_empty("b_txtZip","Please enter billing Zip Code","errordisplay"))return!1;if(!0==checkzip($("b_txtZip"))){if(!0==IsNumeric($("b_txtZip").value))$("errordisplay").style.display="none";else return $("errordisplay").style.display="block",$("errordisplay").innerHTML="Billing Zipcode must be 5 digits",$("b_txtZip").focus(),!1;$("errordisplay").style.display="none"}else return $("errordisplay").style.display= "block",$("errordisplay").innerHTML="Billing Zipcode must be 5 digits",$("b_txtZip").focus(),!1;$("frmadhischool").action=base_url+"index.php/profile/update_profile/";$("frmadhischool").submit()};*/